// Generated by CoffeeScript 1.7.1
(function() {
  var serverConfig;

  serverConfig = {
    _apiServerPath: require('path').dirname(require.main.filename),
    _port: 9999,
    _sessionSecret: 'asdfgk;lgmfgkfgfgdf',
    _cookieSecret: 'werijpweormfk;sfklfsd',
    _mongoConnectStr: 'mongodb://localhost/resshopos',
    _tokenScrete: 'abcd123456789'
  };

  exports.serverConfig = serverConfig;

}).call(this);

//# sourceMappingURL=init.map
